language: node_js

node_js:
  - 12.16.1
  -
sudo: true

branches:
  only:
    - master

deploy:
  # deploy app as front end website
  - provider: heroku
    skip_cleanup: true
    api-key:
      secure: $HEROKU_API_KEY
    app: veronika-medical-record